[project]
name = "game-eavesdropper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "piper-tts>=1.3.0",
    "sounddevice>=0.5.2",
    "vosk>=0.3.45",
    "websockets>=15.0.1",
]
